FROM microsoft/aspnet:1.0.0-rc1-update1-coreclr

COPY project.json /app/
WORKDIR /app
RUN ["dnu", "restore"]
COPY . /app

# default to running the container on port 80
ARG CONTAINER_PORT=80
ARG SERVER_URLS=http://*:$CONTAINER_PORT

ENV SERVER.URLS $SERVER_URLS
EXPOSE $CONTAINER_PORT

ENTRYPOINT ["dnx", "-p", "project.json", "web"]
